### ISSUE TITLE
Please tag release revisions in git

### ISSUE THREAD

**Issue by risicle** [aio-libs/aioftp#153] opened 2022-05-26 20:44 UTC
It doesn't look like there has been a tag for a release revision since 2019. Without these, figuring out the exact source corresponding the the version you're running is painful.

**Comment by pohmelie** [comment] 2022-05-27 11:49
I don't get the problem, you can recognize version via `python -m pip list | grep aioftp`.

**Comment by risicle** [comment] 2022-05-27 17:55
That doesn't give you the source. It tells you a version number (_if_ you're using pip, and not everyone is). If you then need to see the exact source corresponding to that particular version and the git details of what patches have or have not been merged into your version, you have to browse github until you figure it out. It's one of those small things that makes it much easier for a user to productively interact with the project, track down problematic PR merges, etc..

**Comment by pohmelie** [comment] 2022-05-28 05:46
I don't know how you can use lib without pip... actually I can imagine this, but see no reasons for this. Anyway you install package from pypi or your distro repo. They both have version information. Every release have release commit like this https://github.com/aio-libs/aioftp/commit/f705cdfadc3e47266798955fbeb747d0950a9ad6. It is more than enough to recognize exact source point of repository. Tag adds nothing here and useless.

**Comment by risicle** [comment] 2022-05-28 10:13
The most useful thing having tags-for-versions does is make github show at a glance, for any commit, which versions that commit made it into - or if it's only in `master` and hasn't made it in to a release yet.

![Screenshot_20220528_111029](https://user-images.githubusercontent.com/807447/170820861-94410fb4-a2b5-4c91-bc38-dd8a51ae8657.png)

It also allows someone to do e.g. https://github.com/python-ldap/python-ldap/compare/python-ldap-3.1.0...python-ldap-3.3.1

**Comment by pohmelie** [comment] 2022-05-28 14:39
This feature (if someone needs it) works fine for commits: https://github.com/aio-libs/aioftp/compare/9118e912...f705cdfa. Of course this is less readable, but I've never used such comparsions directly in github. Probably, because gitlab is popular for local usage in big companies.

**Comment by pohmelie** [comment] 2022-06-25 13:14
I see likes on your comment, so I add tags.

**Comment by webknjaz** [comment] 2024-10-14 19:17
@pohmelie the reason tags are important is that downstream provenance tools need this for the supply chain transparency and verifying where the source came from. It can allow people to reproduce the builds too.

If you added the required tags already, this should probably be closed.

**Comment by pohmelie** [comment] 2024-10-14 19:29
@webknjaz I add tag for each new release. @risicle should close this, I think.

**Comment by webknjaz** [comment] 2024-10-14 19:31
Is there a transparent way of tracing the source of the non-tagged releases? If yes, those could be added retroactively. Otherwise, there's nothing else that can be done.

**Comment by pohmelie** [comment] 2024-10-14 19:37
There are tags for the last 10 years of development. I think I set almost all of them to proper version If I understand your question correct.

**Comment by webknjaz** [comment] 2024-10-15 02:50
Let's not keep it open, then.

**Closed** 2024-10-15 02:50 UTC
