### ISSUE TITLE
ClientSession.download throws an PathIOError() exception

### ISSUE THREAD

**Issue by mbkr1992** [aio-libs/aioftp#68] opened 2018-01-31 01:04 UTC
While working, I faced an issue, where while downloading if the destination path is something like 'one/two/three/four/' and there exist only one or two sub-directory i.e. 'one/two' it throws this exception. 

`Traceback (most recent call last):
  File "/Users/abubakrdar/anaconda/lib/python3.6/site-packages/aioftp/pathio.py", line 77, in wrapper
    return await coro(*args, **kwargs)
  File "/Users/abubakrdar/anaconda/lib/python3.6/site-packages/aioftp/pathio.py", line 349, in mkdir
    return path.mkdir(parents=parents)
  File "/Users/abubakrdar/anaconda/lib/python3.6/pathlib.py", line 1225, in mkdir
    self._accessor.mkdir(self, mode)
  File "/Users/abubakrdar/anaconda/lib/python3.6/pathlib.py", line 388, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/pub/CDC/observations_germany/climate/daily/solar'`

It works fine if sub-directories in the destination path are just one or two i.e. 'one/two' but I observed that for longer paths it threw this exception so I had to manually create path before downloading files.

**Comment by pohmelie** [comment] 2018-01-31 01:28
What version of `aioftp` do you use? Add code to reproduce this error.

**Comment by mbkr1992** [comment] 2018-01-31 01:33
I'm using aioftp 0.9.0, Following was the code I used.
`await client.download(source=path_for_download, destination=path_for_destination, write_into=False)`
For `path_for_destination = 'downloads/pub/CDC/observations_germany/climate/daily/solar'` I got the afforementioned exception. On my machine only the 'downloads' directory existed.
but when I used `path_for_destination = 'downloads/pub'` it worked fine and created the new direcotry.

**Comment by pohmelie** [comment] 2018-01-31 02:01
Ah, got it… the problem is when path already exist. This can be fixed in `aioftp` pretty easy, since `mkdir` have `exist_ok` argument. Will fix this soon.

**Closed** 2018-02-03 12:19 UTC
